



CREATE TABLE filo.ARTYKULY 
    ( 
     ID NUMBER (10)  NOT NULL , 
     ID_INST VARCHAR2 (10 CHAR) , 
     ID_WYD VARCHAR2 (10 CHAR) , 
     ID_SERIE VARCHAR2 (10 CHAR) , 
     ID_ZESZYTY NUMBER (6) , 
     TYTUL VARCHAR2 (1000 CHAR)  NOT NULL , 
     TYTUL_PL VARCHAR2 (1000 CHAR) , 
     STR_OD NUMBER (4) , 
     STR_DO NUMBER (4) , 
     ID_WYD_OBCE NUMBER (8) , 
     JEZYK CHAR (2 CHAR)  NOT NULL , 
     CZAS_WPR TIMESTAMP DEFAULT systimestamp 
    ) 
;



ALTER TABLE filo.ARTYKULY 
    ADD CONSTRAINT ARTYKULY_PK PRIMARY KEY ( ID ) ;


CREATE TABLE filo.ARTYKULY_KAT 
    ( 
     ARTYKULY_ID NUMBER (10)  NOT NULL , 
     KATEGORIE_ID NUMBER (4)  NOT NULL 
    ) 
;




CREATE TABLE filo.AUTORSTWO 
    ( 
     ID_ART NUMBER (10)  NOT NULL , 
     NR NUMBER (2)  NOT NULL , 
     ID_AUT NUMBER (8)  NOT NULL , 
     ID_INST VARCHAR2 (10 CHAR) 
    ) 
;


CREATE UNIQUE INDEX filo.ARTYKULY_AUT_IDX1 ON filo.AUTORSTWO 
    ( 
     ID_ART ASC , 
     ID_AUT ASC , 
     NR ASC 
    ) 
;
CREATE UNIQUE INDEX filo.ARTYKULY_AUT_IDX2 ON filo.AUTORSTWO 
    ( 
     ID_AUT ASC , 
     ID_ART ASC , 
     NR ASC 
    ) 
;

ALTER TABLE filo.AUTORSTWO 
    ADD CONSTRAINT ARTYKULY_AUT_PK PRIMARY KEY ( ID_ART, NR, ID_AUT ) ;


CREATE TABLE filo.AUTORZY 
    ( 
     ID NUMBER (8)  NOT NULL , 
     NAZWISKO VARCHAR2 (200 CHAR)  NOT NULL , 
     IMIE VARCHAR2 (50 CHAR)  NOT NULL , 
     IMIE2 VARCHAR2 (50 CHAR) , 
     NARODOWOSC CHAR (2 CHAR) 
    ) 
;



ALTER TABLE filo.AUTORZY 
    ADD CONSTRAINT AUTORZY_PK PRIMARY KEY ( ID ) ;


CREATE TABLE filo.BIBLIOGRAFIA 
    ( 
     ID_ART NUMBER (10)  NOT NULL , 
     NR_KOLEJNY NUMBER (3)  NOT NULL , 
     BIB_ART NUMBER (10)  NOT NULL 
    ) 
;

CREATE INDEX filo.BIBLIOGRAFIA_IDX ON filo.BIBLIOGRAFIA 
    ( 
     BIB_ART ASC , 
     ID_ART ASC 
    ) 
;


ALTER TABLE filo.BIBLIOGRAFIA 
    ADD CONSTRAINT BIBLIOGRAFIA_PK PRIMARY KEY ( ID_ART, NR_KOLEJNY ) ;


CREATE TABLE filo.INSTYTUCJE 
    ( 
     ID VARCHAR2 (10 CHAR)  NOT NULL , 
     NAZWA VARCHAR2 (200 CHAR)  NOT NULL 
    ) 
;



ALTER TABLE filo.INSTYTUCJE 
    ADD CONSTRAINT INSTYTUCJE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE filo.KATEGORIE 
    ( 
     ID NUMBER (4)  NOT NULL , 
     OPIS VARCHAR2 (1000 CHAR)  NOT NULL , 
     KATEGORIE_ID NUMBER (4) 
    ) 
;



ALTER TABLE filo.KATEGORIE 
    ADD CONSTRAINT KATEGORIE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE filo.KRAJE 
    ( 
     KOD CHAR (2 CHAR)  NOT NULL , 
     NAZWA VARCHAR2 (50 CHAR)  NOT NULL , 
     FL_AKT CHAR (1 CHAR) DEFAULT 'N'  NOT NULL 
    ) 
;



ALTER TABLE filo.KRAJE 
    ADD CONSTRAINT KRAJE_PK PRIMARY KEY ( KOD ) ;


CREATE TABLE filo.SERIE 
    ( 
     ID_INST VARCHAR2 (10 CHAR)  NOT NULL , 
     ID_WYD VARCHAR2 (10 CHAR)  NOT NULL , 
     ID VARCHAR2 (10 CHAR)  NOT NULL , 
     TYTUL VARCHAR2 (200 CHAR)  NOT NULL , 
     ISSN VARCHAR2 (30 CHAR) 
    ) 
;



ALTER TABLE filo.SERIE 
    ADD CONSTRAINT SERIE_PK PRIMARY KEY ( ID_INST, ID_WYD, ID ) ;


CREATE TABLE filo.SLOWA_KLUCZE 
    ( 
     KLUCZ VARCHAR2 (100)  NOT NULL , 
     ARTYKULY_ID NUMBER (10)  NOT NULL , 
     KRAJ CHAR (2 CHAR)  NOT NULL 
    ) 
;


CREATE INDEX filo.SLOWA_KLUCZE_IDX ON filo.SLOWA_KLUCZE 
    ( 
     KLUCZ ASC 
    ) 
;
CREATE INDEX filo.SLOWA_KLUCZE_IDX_KRAJ ON filo.SLOWA_KLUCZE 
    ( 
     KRAJ ASC 
    ) 
;
CREATE INDEX filo.SLOWA_KLUCZE_IDX_ART ON filo.SLOWA_KLUCZE 
    ( 
     ARTYKULY_ID ASC 
    ) 
;


CREATE TABLE filo.WYDAWNICTWA 
    ( 
     ID_INST VARCHAR2 (10 CHAR)  NOT NULL , 
     ID VARCHAR2 (10 CHAR)  NOT NULL , 
     TYTUL VARCHAR2 (200 CHAR)  NOT NULL 
    ) 
;



ALTER TABLE filo.WYDAWNICTWA 
    ADD CONSTRAINT WYDAWNICTWA_PK PRIMARY KEY ( ID_INST, ID ) ;


CREATE TABLE filo.WYDAWNICTWA_OBCE 
    ( 
     ID NUMBER (8)  NOT NULL , 
     TYP CHAR (3 CHAR) CHECK ( TYP IN ('art', 'roz', 'wyd')) , -- artykuł, rozprawa (?), wydawnictwo
     TYTUL VARCHAR2 (1000 CHAR)  NOT NULL , 
     ROK_WYDANIA NUMBER (4) , 
     NUMER VARCHAR2 (20 CHAR) , 
     KRAJ CHAR (2 CHAR) 
    ) 
;



ALTER TABLE filo.WYDAWNICTWA_OBCE 
    ADD CONSTRAINT WYDAWNICTWA_OBCE_PK PRIMARY KEY ( ID ) ;


CREATE TABLE filo.ZESZYTY 
    ( 
     ID_INST VARCHAR2 (10 CHAR)  NOT NULL , 
     ID_WYD VARCHAR2 (10 CHAR)  NOT NULL , 
     ID_SERIE VARCHAR2 (10 CHAR)  NOT NULL , 
     ID_W_SERII NUMBER (6)  NOT NULL , 
     NR_W_SERII NUMBER (6)  NOT NULL , 
     NR_W_WYDAWNICTWIE NUMBER (8)  NOT NULL , 
     TYTUL_PL VARCHAR2 (1000 CHAR) , 
     ROK_WYDANIA NUMBER (4) , 
     FL_ZWER CHAR (1 CHAR) DEFAULT 'N'  NOT NULL CHECK ( FL_ZWER IN ('N', 'T')) , 
     TYP CHAR (3 CHAR) DEFAULT 'art'  NOT NULL CHECK ( TYP IN ('art', 'hab', 'kon', 'mon', 'ses', 'sym')) , -- zwykły, praca habilitacyjna, konferencja, monografia, sesja, sympozjum naukowe
     NR_TYP VARCHAR2 (20 CHAR) -- niech operator wpisze, nas nie interesuje
    ) 
;



ALTER TABLE filo.ZESZYTY 
    ADD CONSTRAINT ZESZYTY_PK PRIMARY KEY ( ID_INST, ID_WYD, ID_SERIE, ID_W_SERII ) ;

ALTER TABLE filo.ZESZYTY 
    ADD CONSTRAINT ZESZYTY_W_SERII UNIQUE ( ID_INST , ID_WYD , ID_SERIE , NR_W_SERII ) ;

ALTER TABLE filo.ZESZYTY 
    ADD CONSTRAINT ZESZYTY_W_WYDAWNICTWIE UNIQUE ( ID_INST , ID_WYD , NR_W_WYDAWNICTWIE ) ;



ALTER TABLE filo.AUTORSTWO 
    ADD CONSTRAINT ARTYKULY_AUT_ARTYKULY_FK FOREIGN KEY 
    ( 
     ID_ART
    ) 
    REFERENCES filo.ARTYKULY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.AUTORSTWO 
    ADD CONSTRAINT ARTYKULY_AUT_AUTORZY_FK FOREIGN KEY 
    ( 
     ID_AUT
    ) 
    REFERENCES filo.AUTORZY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.AUTORSTWO 
    ADD CONSTRAINT ARTYKULY_AUT_INSTYTUCJE_FK FOREIGN KEY 
    ( 
     ID_INST
    ) 
    REFERENCES filo.INSTYTUCJE 
    ( 
     ID
    ) 
;


ALTER TABLE filo.ARTYKULY_KAT 
    ADD CONSTRAINT ARTYKULY_KAT_ARTYKULY_FK FOREIGN KEY 
    ( 
     ARTYKULY_ID
    ) 
    REFERENCES filo.ARTYKULY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.ARTYKULY_KAT 
    ADD CONSTRAINT ARTYKULY_KAT_KATEGORIE_FK FOREIGN KEY 
    ( 
     KATEGORIE_ID
    ) 
    REFERENCES filo.KATEGORIE 
    ( 
     ID
    ) 
;


ALTER TABLE filo.ARTYKULY 
    ADD CONSTRAINT ARTYKULY_KRAJE_FK FOREIGN KEY 
    ( 
     JEZYK
    ) 
    REFERENCES filo.KRAJE 
    ( 
     KOD
    ) 
;


ALTER TABLE filo.ARTYKULY 
    ADD CONSTRAINT ARTYKULY_WYDAWNICTWA_OBCE_FK FOREIGN KEY 
    ( 
     ID_WYD_OBCE
    ) 
    REFERENCES filo.WYDAWNICTWA_OBCE 
    ( 
     ID
    ) 
;


ALTER TABLE filo.ARTYKULY 
    ADD CONSTRAINT ARTYKULY_ZESZYTY_FK FOREIGN KEY 
    ( 
     ID_INST,
     ID_WYD,
     ID_SERIE,
     ID_ZESZYTY
    ) 
    REFERENCES filo.ZESZYTY 
    ( 
     ID_INST,
     ID_WYD,
     ID_SERIE,
     ID_W_SERII
    ) 
;


ALTER TABLE filo.AUTORZY 
    ADD CONSTRAINT AUTORZY_KRAJE_FK FOREIGN KEY 
    ( 
     NARODOWOSC
    ) 
    REFERENCES filo.KRAJE 
    ( 
     KOD
    ) 
;


ALTER TABLE filo.BIBLIOGRAFIA 
    ADD CONSTRAINT BIBLIOGRAFIA_ARTYKULY_FK FOREIGN KEY 
    ( 
     ID_ART
    ) 
    REFERENCES filo.ARTYKULY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.BIBLIOGRAFIA 
    ADD CONSTRAINT BIBLIOGRAFIA_ARTYKULY_FK2 FOREIGN KEY 
    ( 
     BIB_ART
    ) 
    REFERENCES filo.ARTYKULY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.KATEGORIE 
    ADD CONSTRAINT KATEGORIE_KATEGORIE_FK FOREIGN KEY 
    ( 
     KATEGORIE_ID
    ) 
    REFERENCES filo.KATEGORIE 
    ( 
     ID
    ) 
;


ALTER TABLE filo.SERIE 
    ADD CONSTRAINT SERIE_WYDAWNICTWA_FK FOREIGN KEY 
    ( 
     ID_INST,
     ID_WYD
    ) 
    REFERENCES filo.WYDAWNICTWA 
    ( 
     ID_INST,
     ID
    ) 
;


ALTER TABLE filo.SLOWA_KLUCZE 
    ADD CONSTRAINT SLOWA_KLUCZE_ARTYKULY_FK FOREIGN KEY 
    ( 
     ARTYKULY_ID
    ) 
    REFERENCES filo.ARTYKULY 
    ( 
     ID
    ) 
;


ALTER TABLE filo.SLOWA_KLUCZE 
    ADD CONSTRAINT SLOWA_KLUCZE_KRAJE_FK FOREIGN KEY 
    ( 
     KRAJ
    ) 
    REFERENCES filo.KRAJE 
    ( 
     KOD
    ) 
;


ALTER TABLE filo.WYDAWNICTWA 
    ADD CONSTRAINT WYDAWNICTWA_INSTYTUCJE_FK FOREIGN KEY 
    ( 
     ID_INST
    ) 
    REFERENCES filo.INSTYTUCJE 
    ( 
     ID
    ) 
;


ALTER TABLE filo.WYDAWNICTWA_OBCE 
    ADD CONSTRAINT WYDAWNICTWA_OBCE_KRAJE_FK FOREIGN KEY 
    ( 
     KRAJ
    ) 
    REFERENCES filo.KRAJE 
    ( 
     KOD
    ) 
;


ALTER TABLE filo.ZESZYTY 
    ADD CONSTRAINT ZESZYTY_SERIE_FK FOREIGN KEY 
    ( 
     ID_INST,
     ID_WYD,
     ID_SERIE
    ) 
    REFERENCES filo.SERIE 
    ( 
     ID_INST,
     ID_WYD,
     ID
    ) 
;

CREATE SEQUENCE filo.ARTYKULY_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.ARTYKULY_ID_TRG 
BEFORE INSERT ON filo.ARTYKULY 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.ARTYKULY_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/

CREATE SEQUENCE filo.AUTORZY_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.AUTORZY_ID_TRG 
BEFORE INSERT ON filo.AUTORZY 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.AUTORZY_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/

CREATE SEQUENCE filo.INSTYTUCJE_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.INSTYTUCJE_ID_TRG 
BEFORE INSERT ON filo.INSTYTUCJE 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.INSTYTUCJE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/

CREATE SEQUENCE filo.WYDAWNICTWA_OBCE_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.WYDAWNICTWA_OBCE_ID_TRG 
BEFORE INSERT ON filo.WYDAWNICTWA_OBCE 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.WYDAWNICTWA_OBCE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/

CREATE SEQUENCE filo.ZESZYTY_ID_W_SERII_SEQ 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.ZESZYTY_ID_W_SERII_TRG 
BEFORE INSERT ON filo.ZESZYTY 
FOR EACH ROW 
WHEN (NEW.ID_W_SERII IS NULL) 
BEGIN 
    SELECT filo.ZESZYTY_ID_W_SERII_SEQ.NEXTVAL INTO :NEW.ID_W_SERII FROM DUAL; 
END;
/



