-- Dodatek 1: autoinkrementacja dla kolumny ID tabeli WYDAWNICTWA
CREATE SEQUENCE filo.WYDAWNICTWA_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.WYDAWNICTWA_ID_TRG 
BEFORE INSERT ON filo.WYDAWNICTWA
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.WYDAWNICTWA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/

-- Dodatek 2: autoinkrementacja dla kolumny ID tabeli SERIE
CREATE SEQUENCE filo.SERIE_ID_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER filo.SERIE_ID_TRG 
BEFORE INSERT ON filo.SERIE
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    SELECT filo.SERIE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL; 
END;
/
